"""
Configuration file for LAN Collaboration Suite
FINAL PRODUCTION VERSION - All Issues Fixed
"""

# Server Network Configuration
SERVER_HOST = '0.0.0.0'
TCP_PORT = 5000
UDP_VIDEO_PORT = 5001
UDP_AUDIO_PORT = 5002
TCP_SCREEN_PORT = 5003
TCP_FILE_PORT = 5004

# Buffer Sizes
CHAT_BUFFER_SIZE = 4096
FILE_BUFFER_SIZE = 65536
VIDEO_BUFFER_SIZE = 65535
AUDIO_BUFFER_SIZE = 8192
SCREEN_BUFFER_SIZE = 131072

# Client Limits
MAX_CLIENTS = 100
CONNECTION_TIMEOUT = 300

# Video Settings
VIDEO_WIDTH = 640
VIDEO_HEIGHT = 480
VIDEO_FPS = 20
VIDEO_QUALITY = 75
MAX_FRAME_SIZE = 60000

# Video Grid Layout
VIDEO_GRID_COLS = 3
VIDEO_CELL_WIDTH = 320
VIDEO_CELL_HEIGHT = 240

# Audio Settings
AUDIO_RATE = 44100
AUDIO_CHANNELS = 1
AUDIO_CHUNK = 1024
AUDIO_FORMAT = 'int16'
AUDIO_BYTES_PER_SAMPLE = 2

# Screen Sharing Settings
SCREEN_FPS = 5
SCREEN_QUALITY = 70
SCREEN_SCALE = 0.75
SCREEN_MAX_WIDTH = 1280
SCREEN_MAX_HEIGHT = 720

# File Transfer Settings
MAX_FILE_SIZE = 100 * 1024 * 1024
FILE_CHUNK_SIZE = 65536
SERVER_FILES_DIR = "server_files"
CLIENT_DOWNLOADS_DIR = "downloads"

# Protocol Messages
MSG_CONNECT = "CONNECT"
MSG_DISCONNECT = "DISCONNECT"
MSG_CHAT = "CHAT"
MSG_FILE_META = "FILE_META"
MSG_FILE_DATA = "FILE_DATA"
MSG_FILE_REQUEST = "FILE_REQUEST"
MSG_FILE_LIST = "FILE_LIST"
MSG_FILE_UPLOAD = "FILE_UPLOAD"
MSG_FILE_DOWNLOAD = "FILE_DOWNLOAD"
MSG_FILE_AVAILABLE = "FILE_AVAILABLE"
MSG_FILE_NOTIFICATION = "FILE_NOTIFICATION"
MSG_FILE_UPDATE = "FILE_UPDATE"
MSG_VIDEO = "VIDEO"
MSG_AUDIO = "AUDIO"
MSG_SCREEN_SHARE = "SCREEN"
MSG_VIDEO_START = "VIDEO_START"
MSG_VIDEO_STOP = "VIDEO_STOP"
MSG_AUDIO_START = "AUDIO_START"
MSG_AUDIO_STOP = "AUDIO_STOP"
MSG_SCREEN_START = "SCREEN_START"
MSG_SCREEN_STOP = "SCREEN_STOP"
MSG_SCREEN_REQUEST = "SCREEN_REQUEST"
MSG_SCREEN_GRANT = "SCREEN_GRANT"
MSG_SCREEN_DENY = "SCREEN_DENY"
MSG_SCREEN_UPDATE = "SCREEN_UPDATE"
